api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    eager_loading:
        enabled: true
    collection:
        pagination:
        #    enabled: false #disable pagination and get a big list
            page_parameter_name: _page
            #begin client enabled
            #client_enabled: true #user deside to enable or disable pagination
            #enabled_parameter_name: pagination
            #end client enabled
            items_per_page: 10
            client_items_per_page: true #Disabled by default
            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 20
            partial: false
            client_partial: true
            partial_parameter_name: 'partial'
    exception_to_status:
        App\Exception\EmptyBodyException: 400
        App\Exception\InvalidTokenConfirmationException: 404